#!/bin/bash

mkdir -p images/0 images/1

print_warning1()
{
  echo Warning[1] Parameter has not set: migrate [BU] [URL] [FileList] [Round]
}
print_warning2()
{
  echo Warning[2] Parameter round should start from 2 
}

if [ -z "$4" ] || [ "x$4" = "x0" ] || [ "x$4" = "x1" ] ; then
  echo "" | tee images/0/image.csv | tee images/1/image.csv
  print_warning1
  print_warning2
  while read line ;do 
    if [ ! -z "${line} " ] && [ "x${#line}" != "x0" ] ; then
      statusTest=$(curl -s -o /dev/null $2/"${line}".jpg -w "%{http_code}") 
      if [ "x${statusTest}" = "x404" ]; then
        echo not found image ${line}.jpg 
        echo ${line} | tee -a images/0/image.csv
      fi
      if [ "x${statusTest}" = "x200" ]; then
        #curl -s $2/"${line}".jpg --output images/"$1${line}".jpg 
        echo ${line}.jpg found.
        echo ${line} | tee -a images/1/image.csv
      fi
    fi
  done < $3
fi


if [ ! -z "$4" ] && [ $4 -gt 1 ] &&  [ $4 -lt 11 ]; then
  echo "" | tee images/0/image.csv | tee images/1/image.csv
  for round in $4
  do
    if [ "x${4}" != "x1" ] && [ "x${4}" != "x0" ] ; then
      while read line ;do 
        
        if [ ! -z "${line} " ] && [ "x${#line}" != "x0" ] ;then
          statusTest=$(curl -s -o /dev/null $2/"${line}"_X${round}.jpg -w "%{http_code}") 
          if [ "x${statusTest}" = "x404" ]; then
            echo not found image ${BU}${line}_X${round}.jpg 
            echo ${line}_X${round} | tee -a images/0/image_X${round}.csv
          fi
          if [ "x${statusTest}" = "x200" ]; then
            #curl -s $2/"${line}"_X${round}.jpg --output images/"$1${line}"_X${round}.jpg 
            echo ${BU}${line}_X${round}.jpg found.
            echo ${line}_X${round} | tee -a images/1/image_X${round}.csv
          fi
        fi
      done < $3
    else
      print_warning2
    fi
  done
fi
